version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - mongo

  mongo:
    image: mongo:latest
    #volumes:
      #- ./data/mongodb:/data/db
    ports:
      - "27017:27017"
